-- schema.sql
-- Dataset: thelook_ecommerce (BigQuery Syntax)
-- Version: v4 (Enhanced Analytical Attributes)

---------------------------------------------------------
-- 1. DIMENSION TABLES
---------------------------------------------------------

-- Date Dimension: Generated by DimDateTransformer
CREATE OR REPLACE TABLE `thelook_ecommerce.dim_date` (
    date_key INT64 OPTIONS(description="Standardized date key in YYYYMMDD format"),
    date DATE,
    day INT64,
    month INT64,
    year INT64,
    quarter INT64,
    day_of_week INT64,
    is_weekend BOOLEAN,
    day_name STRING,
    month_name STRING
);

-- Users Dimension: Generated by DimUsersTransformer
CREATE OR REPLACE TABLE `thelook_ecommerce.dim_users` (
    user_key STRING OPTIONS(description="Deterministic hash of user_id"),
    user_id INT64,
    first_name STRING,
    last_name STRING,
    email STRING,
    age INT64,
    age_group STRING,
    customer_status STRING,
    gender STRING,
    state STRING,
    city STRING,
    country STRING,
    postal_code STRING,
    latitude FLOAT64,
    longitude FLOAT64,
    traffic_source STRING,
    created_at TIMESTAMP,
    first_purchase_date TIMESTAMP,
    latest_purchase_date TIMESTAMP
);

-- Products Dimension: Generated by DimProductsTransformer
CREATE OR REPLACE TABLE `thelook_ecommerce.dim_products` (
    product_key STRING OPTIONS(description="Deterministic hash of product_id"),
    product_id INT64,
    name STRING,
    category STRING,
    brand STRING,
    department STRING,
    sku STRING,
    retail_price FLOAT64,
    cost FLOAT64,
    margin_value FLOAT64,
    dc_key STRING OPTIONS(description="Surrogate key linking to Distribution Centers")
);

-- Distribution Centers Dimension: Generated by DimDistributionCentersTransformer
CREATE OR REPLACE TABLE `thelook_ecommerce.dim_distribution_centers` (
    dc_key STRING OPTIONS(description="Deterministic hash of dc_id"),
    id INT64,
    name STRING,
    latitude FLOAT64,
    longitude FLOAT64
);

---------------------------------------------------------
-- 2. FACT TABLES
---------------------------------------------------------

-- Orders Fact: Generated by FactOrdersTransformer
-- Partitioned by created_date_key for performance
CREATE OR REPLACE TABLE `thelook_ecommerce.fact_orders` (
    order_fact_id STRING OPTIONS(description="Deterministic hash of order_id"),
    order_id INT64,
    user_key STRING,
    status STRING,
    gender STRING,
    created_date_key INT64,
    shipped_date_key INT64,
    delivered_date_key INT64,
    returned_date_key INT64,
    num_of_item INT64,
    order_type STRING,
    total_revenue FLOAT64,
    total_cost FLOAT64,
    gross_margin FLOAT64,
    margin_percentage FLOAT64,
    shipping_duration_days INT64,
    delivery_duration_days INT64,
    order_duration_days INT64,
    is_delayed BOOLEAN
)
PARTITION BY RANGE_BUCKET(created_date_key, GENERATE_ARRAY(20190101, 20261231, 10000));

-- Order Items Fact: Generated by FactOrderItemsTransformer
CREATE OR REPLACE TABLE `thelook_ecommerce.fact_order_items` (
    order_item_fact_id STRING OPTIONS(description="Deterministic hash of order_item_id"),
    id INT64,
    order_id INT64,
    user_key STRING,
    product_key STRING,
    dc_key STRING OPTIONS(description="Fulfillment DC Key"),
    sale_price FLOAT64,
    cost FLOAT64,
    gross_margin FLOAT64,
    margin_percentage FLOAT64,
    status STRING,
    is_returned BOOLEAN,
    created_date_key INT64,
    shipped_date_key INT64,
    delivered_date_key INT64,
    returned_date_key INT64
)
PARTITION BY RANGE_BUCKET(created_date_key, GENERATE_ARRAY(20190101, 20261231, 10000));

-- Inventory Fact: Generated by FactInventoryTransformer
CREATE OR REPLACE TABLE `thelook_ecommerce.fact_inventory` (
    inventory_fact_id STRING OPTIONS(description="Deterministic hash of inventory_item_id"),
    id INT64,
    product_key STRING,
    dc_key STRING,
    created_at_key INT64,
    sold_at_key INT64,
    cost FLOAT64,
    days_in_inventory INT64,
    is_sold BOOLEAN
)
PARTITION BY RANGE_BUCKET(created_at_key, GENERATE_ARRAY(20190101, 20261231, 10000));

-- Events Fact: Generated by FactEventsTransformer
-- Partitioned by created_date_key for handling large volume of event data
CREATE OR REPLACE TABLE `thelook_ecommerce.fact_events` (
    event_fact_id STRING OPTIONS(description="Deterministic hash of event_id"),
    event_id INT64,
    user_key STRING,
    sequence_number INT64,
    session_id STRING,
    created_date_key INT64,
    ip_address STRING,
    city STRING,
    state STRING,
    postal_code STRING,
    browser STRING,
    traffic_source STRING,
    uri STRING,
    event_type STRING,
    is_checkout_event BOOLEAN
)
PARTITION BY RANGE_BUCKET(created_date_key, GENERATE_ARRAY(20190101, 20261231, 10000));
