# Debezium Server Configuration

# Sink configuration (Google Cloud Pub/Sub)
debezium.sink.type=pubsub
debezium.sink.pubsub.project.id=cloud-data-project-492514
# Debezium will use the credentials from the environment variable GOOGLE_APPLICATION_CREDENTIALS

# Source configuration (PostgreSQL)
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.database.hostname=postgres-source
debezium.source.database.port=5432
debezium.source.database.user=db_user
debezium.source.database.password=db_password
debezium.source.database.dbname=thelook_db
debezium.source.topic.prefix=thelook
debezium.source.plugin.name=pgoutput

# Use a different slot name to avoid conflict with Kafka Connect
debezium.source.slot.name=thelook_server_slot

# Routing: Gom tất cả các bảng vào duy nhất một topic Pub/Sub: thelook-cdc-events
debezium.source.transforms=route
debezium.source.transforms.route.type=io.debezium.transforms.ByLogicalTableRouter
debezium.source.transforms.route.topic.regex=(.*)
debezium.source.transforms.route.topic.replacement=thelook-cdc-events
debezium.source.transforms.route.key.enforce.uniqueness=false

# Filter (Optional: match the existing set)
debezium.source.schema.include.list=demo
debezium.source.table.include.list=demo.users,demo.products,demo.distribution_centers,demo.inventory_items,demo.orders,demo.order_items,demo.events

# Format configuration
# Pub/Sub sink works best with JSON (default)
debezium.format.value=json
debezium.format.key=json
debezium.format.value.schemas.enable=false
debezium.format.key.schemas.enable=false

# Debezium Server internal storage
quarkus.log.level=INFO
