name: thelook_dwh
version: 1.0.0
config-version: 2

profile: thelook_dwh

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  thelook_dwh:
    staging:
      +materialized: view
      +dataset: thelook_staging
    marts:
      +materialized: table
      +dataset: thelook_datawarehouse

vars:
  raw_source_dataset: thelook_staging
